### VARIABLES ###
expiriment: "GN_XENO_V1"
results: "/Users/chris/Work/Projects/Collab_Gina/analysis/"
threads: 10

### INPUTS ###
# Provide paths to references
# First reference
# Human hg38 primary assembly
hg38Seq: "/Users/chris/Documents/src/hg38/sequence/GRCh38.primary_assembly.genome.fa.gz"
hg38Gtf: "/Users/chris/Documents/src/hg38/annotation/gencode.v46.basic.annotation.gtf"

# Xeno or meta reference
XenoType: "mm"

XenoSeq: "/Users/chris/Documents/src/mm35/fa/GRCm39.primary_assembly.genome.fa.gz"
XenoGtf: "/Users/chris/Documents/src/mm35/gtf/gencode.vM35.basic.annotation.gtf"

# Sequencing samples
samples:
 S2_3h: "/Users/chris/Work/Projects/Collab_Gina/data/Xeno_S2.fq.gz"
 S3_5h: "/Users/chris/Work/Projects/Collab_Gina/data/Xeno_S3.fq.gz"
 S4_5h: "/Users/chris/Work/Projects/Collab_Gina/data/Xeno_S4.fq.gz"